---
- hosts: localhost
  become: true
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: copying
      copy:
        src: index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'
    - name: starting
      service:
        name: apache2
        state: restarted
