- name: Installing and configuring server
  hosts: liveServer
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install PHP and FPM
      apt:
        name:
          - php8.3
          - php8.3-fpm
        state: present

    - name: Start and enable PHP-FPM
      service:
        name: php8.3-fpm
        state: started
        enabled: yes

    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes
