- name: installing LEMP
  hosts: myserver
  become: true
  tasks:
     - name: update all packages
       yum:
        name: '*'
        state: latest
       when: ansible_distribution== 'Amazon'
 
     - name: update all packages
       apt:
        name: '*'
        state: latest
       when: ansible_distribution== 'ubuntu'
 
     - name: installing nginx
       apt:
         name: ['nginx','php8.3', 'php8.3-fpm', 'mariadb-server']
         state: present
       when: ansible_distribution== 'ubuntu'
       notify:
        - restart nginx
        - restart mariadb
 
     - name: installing nginx
       yum:
         name: ['nginx','php8.3', 'php8.3-fpm', 'mariadb105-server']
         state: present
       when: ansible_distribution== 'Amazon'
       notify:
        - restart nginx
        - restart mariadb
 
     - name: start nginx
       service:
        name: nginx
        state: started
       notify: restart nginx
 
     - name: start mysql
       service:
        name: mariadb
        state: started
       notify: restart mariadb
 
  handlers:
     - name: restart nginx
       service:
         name: nginx
         state: restarted
 
     - name: restart mariadb
       service:
         name: mariadb
         state: restarted
 
     - name: restart php8.3-fpm
       service:
         name: php8.3-fpm
         state: restarted
